#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:sqlserver://localhost:1433;database=CLOUD_DB01;encrypt=true;trustServerCertificate=true;
#    username: sa1
#    password: P@ssw0rd
#    hikari:
#      poolName: Hikari
#      auto-commit: false
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true